name: Metrics
on:
  schedule: [{cron: "0 15 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          config_timezone: Japan
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_colors: "python: #346E9E, typescript: #007ACC"
          plugin_languages_details: percentage
          plugin_languages_sections: most-used, recently-used
          commits_authoring: 60635066+midorimici@users.noreply.github.com
